# USAGE
#
# This workflow is triggered whenever a pull_request event is triggered within
# the _smartcontractkit/chainlink_ repository. Then, the status of this workflow
# is returned back and propagated. See https://github.com/marketplace/actions/trigger-workflow-and-wait for more information
# 
# PURPOSE
# This checks if breaking changes are made to the schema within a PR in the 
# smartcontractkit/chainlink repo, then fails if so. Schema changes should
# never be breaking. See https://graphql.org/learn/best-practices/#versioning

name: Chainlink CI
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: The chainlink ref to test against

jobs:
  detect-gql-breaking-changes:
    name: Detect GQL Breaking Changes
    runs-on: ubuntu-latest
    steps: 
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Detect GQL Breaking Changes 
        continue-on-error: true

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Run yarn install
        run: yarn install --frozen-lockfile
      
      - name: Test setup 
        run: yarn codegen
        env:
          GH_TOKEN: ${{ github.token }}
          REPO_REF: ${{ inputs.ref }}
