name: CI

on:
  push:

jobs:
  unit-tests:
    strategy:
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
    name: Unit Tests ${{ matrix.shard }}
    runs-on: ubuntu-latest
    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Unit Tests ${{ matrix.shard }}
        continue-on-error: true

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Run yarn install
        run: yarn install --frozen-lockfile

      - name: Setup project
        run: yarn setup
        env:
          GH_TOKEN: ${{ github.token }}
          
      - name: Run tests
        run: yarn run test:ci --shard=${{ matrix.shard }}
        
      # - name: Upload coverage
      #   run: ./bin/codecov -s operator_ui/coverage
